### PR TITLE
Reimplemented as platform with a background refresh

### PR DESCRIPTION
**Pull request by misncz**

### CODE REVIEW

**Comment by F4stFr3ddy** [comment]
I will do proper testing tomorrow.

**Comment by F4stFr3ddy** [comment]
Why was it closed?

**Comment by misncz** [comment]
> Why was it closed?

Because I wanted to ask you to test it first :-) Once you say it's ok I'll raise it again

**Comment by F4stFr3ddy** [comment]
This behaviour is one of the challenges with any home automation, controlling with 2 methods, in this case the Home app and the Jablotron app, my findings:  
- Whenever I open the Home app it doesn't check status of the Alarm, so for some time Home apps says the Alarm is armed but in reality its not. The previous version refreshed upon opening Home app. 

- Once Home app detects that the Alarm is (dis)armed it will remain in a stat of (dis)arming untill the app is re-opened.


**BUG(S)**  

It did perform the command but got an error with logging:  
  
```
[2/9/2019, 10:20:58 PM] [Jablotron] Switching section pgm_2 (using pgm_2) to new state: set
[2/9/2019, 10:20:59 PM] [Jablotron] { status: false,
  error_status: 'error_dialog',
  error_type: 'dialog',
  error_message: 'Operation failed',
  checksum: '03c779fc11fa1e12aa80369fd1a49ab0',
  server_id: '2917516-1549750859',
  client_id: null }
/opt/node/lib/node_modules/homebridge-jablotron/lib/jablotron.js:122
            this.log(error);
                 ^

TypeError: this.log is not a function
    at Object.tryHandleError (/opt/node/lib/node_modules/homebridge-jablotron/lib/jablotron.js:122:18)
    at /opt/node/lib/node_modules/homebridge-jablotron/lib/jablotron.js:93:30
    at /opt/node/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:23:17
    at IncomingMessage.<anonymous> (/opt/node/lib/node_modules/homebridge-jablotron/lib/jablotron-client.js:54:17)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  ```

**Comment by misncz** [comment]
Thank you for the fixes - for some time I'm already looking at "arming" thing. As for initial state - upon homebridge startup it triggers the refresh ASAP but if you open home app very soon (which is something that won't happen too often I guess) it will show the default states because refresh is pending still

**Comment by misncz** [comment]
Looks like I was able to fix "Arming..." and "Disarming..." status. Now when I have Homekit app opened and externally arm/disarm Jablotron segment it properly updates the state in Homekit without getting stuck on either "Arming..." or "Disarming..." state. Please give it a try

**Comment by F4stFr3ddy** [comment]
Awesome work, bug fixed indeed! I had version the build from yesterday run but it crashed during the night. If this one makes it trough the night I'll merge and publish to NPM.

**Comment by misncz** [comment]
> Awesome work, bug fixed indeed! I had version the build from yesterday run but it crashed during the night. If this one makes it trough the night I'll merge and publish to NPM.

If it crashed, do you have the logs available? I'm running homebridge on startup using the method described at https://timleland.com/setup-homebridge-to-start-on-bootup/
This method has the big advantage of automatic homebridge restart upon a crash and logging to syslog

**Comment by F4stFr3ddy** [comment]
I'm running it with screen, starts once the Pi is booted but doesn't restart. I never had it crash actually unless I'm running test versions on my test Pi. I forgot to record the error, but it was complaining about the address and port. However it also complained about a key not available in the response.

**Comment by misncz** [comment]
> I'm running it with screen, starts once the Pi is booted but doesn't restart. I never had it crash actually unless I'm running test versions on my test Pi. I forgot to record the error, but it was complaining about the address and port. However it also complained about a key not available in the response.

Interesting, do you have more details available please?

**Comment by F4stFr3ddy** [comment]
> > I'm running it with screen, starts once the Pi is booted but doesn't restart. I never had it crash actually unless I'm running test versions on my test Pi. I forgot to record the error, but it was complaining about the address and port. However it also complained about a key not available in the response.
> 
> Interesting, do you have more details available please? It could be some networking issues and not properly handled error in https communication

Sorry I don't have any of the logs. It was getting an error on this:
`var segments = response['data']['service_data'][0]['data'][0]['data']['segments']`

Where the data wasn't a list, so yes we could improve the handling of an error in such a case as currently it was just logged to the console. I suspect it was indeed related to the network, however it was present for multiple hours and finally led to Homebridge going down.

**Comment by misncz** [comment]
> > > I'm running it with screen, starts once the Pi is booted but doesn't restart. I never had it crash actually unless I'm running test versions on my test Pi. I forgot to record the error, but it was complaining about the address and port. However it also complained about a key not available in the response.
> > 
> > 
> > Interesting, do you have more details available please? It could be some networking issues and not properly handled error in https communication
> 
> Sorry I don't have any of the logs. It was getting an error on this:
> `var segments = response['data']['service_data'][0]['data'][0]['data']['segments']`
> 
> Where the data wasn't a list, so yes we could improve the handling of an error in such a case as currently it was just logged to the console. I suspect it was indeed related to the network, however it was present for multiple hours and finally led to Homebridge going down.

I added more safe response parsing and log output in case the response received doesn't meet expected format

**Pull request merged**
